const titleCard = [
  "",
  "░█████╗░██╗░░░░░██╗░█████╗░██╗░░██╗███████╗██████╗░██╗░░░██╗",
  "██╔══██╗██║░░░░░██║██╔══██╗██║░██╔╝██╔════╝██╔══██╗╚██╗░██╔╝",
  "██║░░╚═╝██║░░░░░██║██║░░╚═╝█████═╝░█████╗░░██████╔╝░╚████╔╝░",
  "██║░░██╗██║░░░░░██║██║░░██╗██╔═██╗░██╔══╝░░██╔══██╗░░╚██╔╝░░",
  "╚█████╔╝███████╗██║╚█████╔╝██║░╚██╗███████╗██║░░██║░░░██║░░░",
  "░╚════╝░╚══════╝╚═╝░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░",
];
const titleCardSmall = ["CLICKERY"];
const mainText = [
  "",
  "",
  "--",
  "Automating your workflow with Clickery!",
  "",
  "Made with ❤ by <a href='https://github.com/MZaFaRM'>Muhammed Zafar</a>",
  "--",
  "",
  "",
  "Type 'help' to see list of available commands, and navigate through the webpage!",
  "",
  "--",
  "",
  "The project is open-source 🎉 type 'repo' to check out the repository.",
  "",
  "Credits to <a href='https://dev.to/m4tt72'>Yassine Fathi</a> for website ui inspiration and theme",
  "--",
];

const gettingStarted = [
  "",
  "",
  "<span class='pre'>⠀██╗</span>",
  "<span class='pre'>███║</span>",
  "<span class='pre'>╚██║</span>",
  "<span class='pre'> ██║</span>",
  "<span class='pre'> ██║</span>",
  "<span class='pre'> ╚═╝</span>\t\tEnsure that you have the latest <a href='https://www.python.org/downloads/'>python</a> on your PC.",
  "Optionally, download <a href='https://www.tutorialspoint.com/sqlite/sqlite_installation.htm'>SQLite</a> too, for better experience!",
  "",
  "",
  "",
  "",
  "<span class='pre'>██████╗ </span>",
  "<span class='pre'>╚════██╗</span>",
  "<span class='pre'> █████╔╝</span>",
  "<span class='pre'>██╔═══╝ </span>",
  "<span class='pre'>███████╗</span>",
  "<span class='pre'>╚══════╝</span>\t\tNow open a terminal and clone the project through <a class='copy-clip'>https://github.com/MZaFaRM/Clickery.git</a> Or just download and extract the Project\'s <a href='https://github.com/MZaFaRM/Clickery/archive/refs/heads/main.zip'>Zip file</a>!",
  "",
  "",
  "",
  "",
  "<span class='pre'>██████╗ </span>",
  "<span class='pre'>╚════██╗</span>",
  "<span class='pre'> █████╔╝</span>",
  "<span class='pre'> ╚═══██╗</span>",
  "<span class='pre'>██████╔╝</span>",
  "<span class='pre'>╚═════╝ </span>\t\tCreate a virtual environment through <a class='copy-clip'>python -m venv myenv</a> and activate the myenv through <a class='copy-clip'>source venv/bin/activate</a>",
  "",
  "",
  "",
  "",
  "<span class='pre'>██╗  ██╗</span>",
  "<span class='pre'>██║  ██║</span>",
  "<span class='pre'>███████║</span>",
  "<span class='pre'>╚════██║</span>",
  "<span class='pre'>     ██║</span>",
  "<span class='pre'>     ╚═╝</span>\t\tRun setup.py through <a class='copy-clip'>python setup.py</a> and then run <a class='copy-clip'>python main.py</a>",
  "",
  "",
  "",
  "",
  "<span class='pre'>███████╗</span>",
  "<span class='pre'>██╔════╝</span>",
  "<span class='pre'>███████╗</span>",
  "<span class='pre'>╚════██║</span>",
  "<span class='pre'>███████║</span>",
  "<span class='pre'>╚══════╝</span>\t\t🎉 Congrats! you have successfully run the project!", 
  "If you encountered any issues please don't hesitate to reach out!",
  "",
  "",
];

export { titleCard, mainText, titleCardSmall, gettingStarted };
